//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewtableApiDataconsumeproject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        //internal int id;

        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PassWord { get; set; }
        public string Email { get; set; }
        public Nullable<long> Mobile { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public string Hobbies { get; set; }
        public string Date { get; set; }
        public string Country { get; set; }
    }
}
